# Generated by Django 4.1.5 on 2024-02-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_prefertable_room_teachertable_dutyallotment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=20),
        ),
    ]
