# Generated by Django 3.2.12 on 2024-03-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyallotment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.course'),
            preserve_default=False,
        ),
    ]
