# Generated by Django 4.1.5 on 2024-06-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_dutyallotment_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="exam_id",
        ),
    ]
