# Generated by Django 4.1.5 on 2024-06-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_timetable"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="timetable",
            new_name="Timetable1",
        ),
    ]
