# Generated by Django 4.1.5 on 2024-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0009_remove_prefertable_room_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Optedtb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user_id", models.IntegerField()),
                ("user_name", models.CharField(max_length=40)),
            ],
        ),
    ]
